### PR TITLE
Fix controller activation crash on macOS (Fixes #604)

### LINKED ISSUE #604: Async controllers
# Motivation

An asynchronous controller is a controller that for some reason cannot (or we don’t want to) perform the operations needed in an update() call.
For instance if ros control is running at 100Hz, the sum of the execution time of all controllers update() calls must be below 10ms. If a controller requires 15ms it cannot be executed synchronously without affecting the whole ros control update rate.

For more, please see https://github.com/ros-controls/roadmap/pull/48

### PR DESCRIPTION
**Pull request by idesign0**
This PR resolves [#604](https://github.com/ros-controls/gz_ros2_control/issues/604), which caused a runtime crash on macOS during controller activation.

The issue stemmed from the use of std::defer_lock with std::unique_lock prior to calling wait() on a condition variable. On macOS, the underlying libc++ implementation strictly enforces that a mutex must be locked before invoking wait(). Since defer_lock does not acquire the lock, this led to undefined behavior and a crash at runtime.

This PR corrects the locking behavior by ensuring the mutex is properly locked before wait() is called, making the code safe and portable across platforms, including macOS.

### CODE REVIEW

File: controller_manager/src/controller_manager.cpp [hunk 1]
```diff
@@ -1852,9 +1852,17 @@ controller_interface::return_type ControllerManager::switch_controller_cb(
...
   RCLCPP_DEBUG(get_logger(), "Requested atomic controller switch from realtime loop");
-  std::unique_lock<std::mutex> switch_params_guard(switch_params_.mutex, std::defer_lock);
+  std::unique_lock<std::mutex> switch_params_guard(switch_params_.mutex, std::try_to_lock);
+  if (!switch_params_guard.owns_lock())
+  {
+    RCLCPP_ERROR(
+      get_logger(), "Could not lock switch mutex, controller switch failed!");
+    clear_requests();
+    return controller_interface::return_type::ERROR;
+  }
```
Comment (saikishor) [inline controller_manager/src/controller_manager.cpp]: Can you check if we can delete the defer_lock part?

Comment (idesign0) [reply controller_manager/src/controller_manager.cpp]: I've actually removed the defer_lock usage from my local fork a while ago, and it’s been working reliably across multiple frameworks — including nav2. It’s been over a month now, and I haven’t encountered any related issues.

Normally, defer_lock is used when there's code between creating and locking the mutex. Here, the code went straight to cv.wait() without locking, so I used try_to_lock to ensure the mutex is held before waiting.

and as far as I checked, this is the only defer_lock usage in the controller_manager code.

**Comment by idesign0** [comment]
@ christophfroehlich 

Thanks! Yes, pre-commit is available on macOS — I’ll install it and run the checks again to fix the current issues.
Also, adding a GitHub workflow for macOS sounds like a great idea. I’ll look into it and open a separate PR for that.

File: controller_manager/src/controller_manager.cpp (hunk 1 above)
Comment (saikishor) [reply controller_manager/src/controller_manager.cpp]: I don't think it makes sense to fail when you are unable to lock the mutex; I believe the correct behaviour should be to wait, which is the default behaviour when you get the lock.

Comment (idesign0) [reply controller_manager/src/controller_manager.cpp]: @saikishor Agreed — I’ll remove the failure block and replace try_to_lock with the default lock so it waits as expected. Thanks for pointing it out!

Comment (saikishor) [inline controller_manager/src/controller_manager.cpp]:
```suggestion
  std::unique_lock<std::mutex> switch_params_guard(switch_params_.mutex);
```

Comment (saikishor) [reply controller_manager/src/controller_manager.cpp]: @idesign0 Here you go ;)

**Comment by idesign0** [comment]
@saikishor thanks! 😇 kinda new to all of this (PR and code reviews) so misinterpreted your comment on defer_lock() comment. 😅

**Review by saikishor — DISMISSED** [review]

**Comment by idesign0** [comment]
will add pre-commits check and push again.

**Comment by idesign0** [comment]
@christophfroehlich 

Hi, could this be considered for backport to the `humble` branch as well?

**Comment by saikishor** [comment]
> @christophfroehlich 
> 
> Hi, could this be considered for backport to the `humble` branch as well?
> 

I'm not sure if the Humble carries the same logic at the switch controllers level

**Comment by idesign0** [comment]
@saikishor 

Yes switching controllers logic, atomic controller switching, is  pretty similar to the upstream.

**Comment by saikishor** [comment]
@idesign0 Let's first release to rolling and Jazzy and later after 1 release cycle, we can backport it to humble

**Comment by idesign0** [comment]
> @idesign0 Let's first release to rolling and Jazzy and later after 1 release cycle, we can backport it to humble
> 
> 

Alright! 👍
