### PR TITLE
Fix flaky transmission_interface tests by making them deterministic.

### LINKED ISSUE #1555: Flaky transmission_interface tests
https://github.com/ros-controls/ros2_control_ci/actions/runs/9311761772

```
    -- run_test.py: invoking following command in '/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/transmission_interface':
     - /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/transmission_interface/test_four_bar_linkage_transmission --gtest_output=xml:/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/transmission_interface/test_results/transmission_interface/test_four_bar_linkage_transmission.gtest.xml
    Running main() from gmock_main.cc
    [==========] Running 8 tests from 4 test suites.
    [----------] Global test environment set-up.
    
    [----------] 1 test from BlackBoxTest
    [ RUN      ] BlackBoxTest.IdentityMap
    /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/ros2_control/transmission_interface/test/four_bar_linkage_transmission_test.cpp:174: Failure
    Value of: ref_val[1]
    Expected: is approximately 480.33728696123558 (absolute error <= 1.0000000000000001e-05)
      Actual: 480.337 (of type double), which is -1.20111e-05 from 480.337
    [  FAILED  ] BlackBoxTest.IdentityMap (239 ms)
```

### PR DESCRIPTION
**Pull request by sgmurray**
Fixes #1555 

The transmission_interface tests would give non deterministic spurious failures. The non determinism was because tests were randomly generated using the system time to seed the random number generator. The spurious failures were due to occasionally occurring tiny rounding errors from floating point math.

By seeding the random number generator the tests become deterministic and we avoid the spurious failures. 
Additionally, changing the order of some of the multiplications seems to reduce the rounding error.

Contributions via pull requests are much appreciated. Before sending us a pull request, please ensure that:

1. Limited scope. Your PR should do one thing or one set of things. Avoid adding “random fixes” to PRs. Put those on separate PRs.
2. Give your PR a descriptive title. Add a short summary, if required.
3. Make sure the pipeline is green.
4. Don’t be afraid to request reviews from maintainers.
5. New code = new tests. If you are adding new functionality, always make sure to add some tests exercising the code and serving as live documentation of your original intention.

To send us a pull request, please:

- [ ] Fork the repository.
- [ ] Modify the source; please focus on the specific change you are contributing. If you also reformat all the code, it will be hard for us to focus on your change.
- [ ] Ensure local tests pass. (`colcon test` and `pre-commit run` (requires you to install pre-commit by `pip3 install pre-commit`)
- [ ] Commit to your fork using clear commit messages.
- [ ] Send a pull request, answering any default questions in the pull request interface.
- [ ] Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.

### CODE REVIEW

File: transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp [hunk 1]
```diff
@@ -289,7 +289,7 @@ inline void FourBarLinkageTransmission::actuator_to_joint()
 
     joint_eff[0].set_value(jr[0] * act_eff[0].get_value() * ar[0]);
     joint_eff[1].set_value(
-      jr[1] * (act_eff[1].get_value() * ar[1] - act_eff[0].get_value() * ar[0] * jr[0]));
+      jr[1] * (act_eff[1].get_value() * ar[1] - jr[0] * act_eff[0].get_value() * ar[0]));
```
Comment (christophfroehlich) [inline transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp:292]: Was this change intentional?

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
Thanks for picking this up! 

Please fix the pre-commit errors (you can install it locally and run the tests before you push).

File: transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp (hunk 1 above)
Comment (sgmurray) [reply transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp:292]: Yes. It seems to reduce the rounding error. Notice how jr[0], act_eff[0], a[0] are now in the same order as they are on line 290.

Comment (christophfroehlich) [reply transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp:292]: ok, I see.

**Review by christophfroehlich — APPROVED** [review]

**Review by bmagyar — APPROVED** [review]
thank you!
